# Generated by Django 3.1.7 on 2021-03-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_Name', models.CharField(max_length=256)),
                ('center_desc', models.TextField()),
                ('center_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
