# Generated by Django 3.1.7 on 2021-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_id',
            field=models.IntegerField(default=0),
        ),
    ]
