# Generated by Django 3.1.7 on 2021-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0003_auto_20210314_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_desc',
            field=models.TextField(),
        ),
    ]
